### ISSUE TITLE
load module cplpy 

### ISSUE THREAD

**Issue by marchandpatrick** [Crompulence/CPL_APP_LAMMPS-DEV#1]
in  CPL_APP_LAMMPS-DEV/test/constant_force/CFD_single_ball.py 

I have not been able to load module cplpy required in line:
from cplpy import CPL

How to solve this?

**Comment by edwardsmith999** [comment]
You need to

source SOURCEME.sh

This adds the python bindings to your path. CPL isn't installed so you can choose how/where you add it, instead you add to path with source

Note this error also occurs if using python 3 (currently we only support python 2.7 but can look into porting if this is important)

**Comment by edwardsmith999** [comment]
We now support Python3 so i'll close issue
